language: java
#
# use the container based infra and get benefits of the cache
#
sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo wget --no-check-certificate -O /usr/local/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64
  - sudo chmod +x /usr/local/bin/confd
  - docker pull nodevops/maven-fury-confd
  - id
  - pwd

# skip 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
install: /bin/true

script:
  - chmod +x ./scripts/travis_build.sh
  - ./scripts/travis_build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)


