language: java
#
# use the container based infra and get benefits of the cache
#
sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - mkdir -p $HOME/.local/bin
  - wget --no-check-certificate -O $HOME/.local/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64
  - chmod +x $HOME/.local/bin/confd

# skip 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
install: /bin/true

script:
  - chmod +x ./scripts/travis_build.sh
  - ./scripts/travis_build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)


